steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/microservicios-494715/image-registry/auth-ms",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
    env:
    - 'AUTH_DATABASE_URL=mongodb+srv://admin:admin@authms.uxfrmwa.mongodb.net/AuthDb'
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/microservicios-494715/image-registry/auth-ms",
      ]
options:
  logging: CLOUD_LOGGING_ONLY